services:
  - type: web
    name: voice-cloning-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: models
      mountPath: /opt/render/project/src/saved_models
      sizeGB: 50 