services:
  - type: web
    name: voice-cloning-api
    env: docker
    buildCommand: "docker build -t voice-clone ."
    startCommand: "docker run -p $PORT:5000 voice-clone"
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: GUNICORN_TIMEOUT
        value: 900
      - key: GUNICORN_WORKERS
        value: 1
    healthCheckPath: /api/health
    autoDeploy: true
    plan: standard